name: Release

on: 
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Download Whisper model
        run: |
          mkdir -p models
          curl -L -o models/ggml-tiny.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin

      - name: Build and bundle Tauri app
        run: |
          cd rust
          cargo tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WhisperLite-${{ matrix.platform }}
          path: rust/target/release/bundle/
